title: "VibeCopilot 完整开发路线图"
description: "VibeCopilot项目的完整开发路线图配置，组织三个主要开发阶段的路线图文件"
last_updated: "2024-06-02"
themes:
  - id: "theme1"
    name: "规则引擎基础阶段"
    roadmap_file: "rule_engine_roadmap.yaml"
  - id: "theme2"
    name: "VibeCopilot自动化阶段"
    roadmap_file: "vibe_copilot_roadmap.yaml"
  - id: "theme3"
    name: "CDDRG高级自主性阶段"
    roadmap_file: "cddrg_engine_roadmap.yaml"
current_theme: "theme2"
