version: 1
formatters:
  workflow:
    format: "%(asctime)s - %(name)s - [%(workflow_id)s] - %(levelname)s - %(message)s"
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  workflow_file:
    class: logging.FileHandler
    formatter: workflow
    filename: logs/workflow/workflow.log
    encoding: utf-8
  default_file:
    class: logging.FileHandler
    formatter: default
    filename: logs/app.log
    encoding: utf-8
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  workflow:
    level: INFO
    handlers: [workflow_file, console]
    propagate: false
  default:
    level: INFO
    handlers: [default_file, console]
    propagate: false

root:
  level: INFO
  handlers: [default_file, console]
