# 命令检查配置

common_config:
  command_prefix: "vibecopilot"
  default_timeout: 30
  max_retries: 3

performance:
  max_response_time: 30  # 秒
  check_response_time: true

output_format:
  check_json_format: true
  check_help_format: true
  check_error_format: true

command_groups:
  - name: "roadmap"
    description: "路线图管理命令"
    config_file: "roadmap_commands.yaml"
    critical: true
