# 命令检查配置

common_config:
  command_prefix: "vibecopilot"
  default_timeout: 30
  max_retries: 3

performance:
  max_response_time: 30  # 秒
  check_response_time: true

output_format:
  check_json_format: true
  check_help_format: true
  check_error_format: true

command_groups:
  - name: "roadmap"
    description: "路线图管理命令"
    config_file: "roadmap_commands.yaml"
    critical: true
  - name: "task"
    description: "任务管理命令"
    config_file: "task_commands.yaml"
    critical: true
  - name: "memory"
    description: "记忆管理命令"
    config_file: "memory_commands.yaml"
    critical: true
  - name: "flow_session"
    description: "流程会话管理命令"
    config_file: "flow_session_commands.yaml"
    critical: true
  - name: "rule"
    description: "规则管理命令"
    config_file: "rule_commands.yaml"
    critical: true
  - name: "db"
    description: "数据库管理命令"
    config_file: "db_commands.yaml"
    critical: true
  - name: "flow"
    description: "流程管理命令"
    config_file: "flow_commands.yaml"
    critical: true
  - name: "status"
    description: "状态管理命令"
    config_file: "status_commands.yaml"
    critical: true
  - name: "template"
    description: "模板管理命令"
    config_file: "template_commands.yaml"
    critical: true
