# 工作流会话命令组配置

commands:
  "flow session list":
    description: "列出所有会话"
    subcommands:
      "--verbose":
        description: "显示详细信息"
        type: "flag"
      "--format":
        description: "输出格式"
        values: ["yaml", "text", "json"]
      "--status":
        description: "按状态筛选会话"
        type: "string"
      "--flow":
        description: "按工作流ID筛选会话"
        type: "string"
    expected_output: ["会话列表"]
    timeout: 5
    critical: true

  "flow session show":
    description: "显示特定会话的详细信息"
    subcommands:
      "ID_OR_NAME":
        description: "会话ID或名称"
        type: "string"
        required: false
      "--verbose":
        description: "显示详细信息"
        type: "flag"
      "--format":
        description: "输出格式"
        values: ["yaml", "text", "json"]
    expected_output: ["会话详情"]
    timeout: 5
    critical: true

  "flow session create":
    description: "创建并启动新会话"
    subcommands:
      "--flow":
        description: "工作流ID"
        type: "string"
        required: true
      "--name":
        description: "会话名称"
        type: "string"
      "--task":
        description: "关联的任务ID"
        type: "string"
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["会话创建成功"]
    timeout: 10
    critical: true

  "flow session close":
    description: "结束会话"
    subcommands:
      "ID_OR_NAME":
        description: "会话ID或名称"
        type: "string"
        required: false
      "--reason":
        description: "会话结束原因"
        type: "string"
      "--force":
        description: "强制结束，不提示确认"
        type: "flag"
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["会话已结束"]
    timeout: 5
    critical: true

  "flow session switch":
    description: "切换当前活动会话"
    subcommands:
      "ID_OR_NAME":
        description: "会话ID或名称"
        type: "string"
        required: false
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["已切换会话"]
    timeout: 5
    critical: true

  "flow session update":
    description: "更新会话属性"
    subcommands:
      "ID_OR_NAME":
        description: "会话ID或名称"
        type: "string"
        required: false
      "--name":
        description: "新的会话名称"
        type: "string"
      "--status":
        description: "设置会话状态"
        values: ["ACTIVE", "PAUSED", "COMPLETED", "CLOSED"]
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["会话已更新"]
    timeout: 5
    critical: true

  "flow session delete":
    description: "永久删除会话（不可恢复）"
    subcommands:
      "ID_OR_NAME":
        description: "会话ID或名称"
        type: "string"
        required: false
      "--force":
        description: "强制删除，不提示确认"
        type: "flag"
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["会话已删除"]
    timeout: 5
    critical: true

# 会话组特定配置
group_config:
  max_concurrent_sessions: 3   # 最大并发会话数
  session_timeout: 3600       # 会话超时时间（秒）
  auto_save: true            # 是否自动保存会话状态
  keep_history: true         # 是否保留历史记录

# 会话验证配置
validation:
  check_workflow: true       # 检查工作流有效性
  check_resources: true      # 检查资源可用性
  validate_params: true      # 验证参数
  check_permissions: true    # 检查权限
