name: memory
description: "知识库管理命令，支持内容存储、检索和管理"
type: group

commands:
  "memory list":
    description: "列出知识库内容"
    subcommands:
      "folder":
        description: "筛选特定目录的内容"
        required: false
      "--format":
        description: "输出格式 (json/text)"
        values: ["json", "text"]
        default: "text"
        required: false
      "--verbose":
        short: "v"
        description: "提供详细输出"
        type: "flag"
        required: false
      "--agent-mode":
        description: "启用agent优化的输出格式"
        type: "flag"
        required: false

  "memory show":
    description: "显示知识库内容详情"
    subcommands:
      "path":
        description: "文档路径或标识符"
        required: true
      "--format":
        description: "输出格式 (json/text)"
        values: ["json", "text"]
        default: "text"
        required: false
      "--verbose":
        short: "v"
        description: "提供详细输出"
        type: "flag"
        required: false
      "--agent-mode":
        description: "启用agent优化的输出格式"
        type: "flag"
        required: false

  "memory create":
    description: "创建知识库内容"
    subcommands:
      "--title":
        description: "文档标题"
        required: true
      "--folder":
        description: "存储目录"
        required: true
      "--tags":
        description: "标签列表，逗号分隔"
        required: false
      "--content":
        description: "要保存的内容（如果不提供，将使用当前对话内容）"
        required: false
      "--verbose":
        short: "v"
        description: "提供详细输出"
        type: "flag"
        required: false
      "--agent-mode":
        description: "启用agent优化的输出格式"
        type: "flag"
        required: false

  "memory search":
    description: "语义搜索知识库"
    subcommands:
      "--query":
        description: "搜索关键词"
        required: true
      "--type":
        description: "内容类型"
        required: false
      "--format":
        description: "输出格式 (json/text)"
        values: ["json", "text"]
        default: "text"
        required: false
      "--verbose":
        short: "v"
        description: "提供详细输出"
        type: "flag"
        required: false
      "--agent-mode":
        description: "启用agent优化的输出格式"
        type: "flag"
        required: false

# 配置验证
validation:
  check_commands: true
  validate_examples: true
  check_links: true
  verify_format: true

# 格式化配置
format_config:
  use_rich: true
  use_color: true
  use_emoji: true
  use_tables: true
