# Roadmap命令组配置

commands:
  "roadmap sync":
    description: "在本地路线图和GitHub Project之间同步数据"
    arguments:
      - name: "operation"
        description: "同步操作类型 (push: 本地 -> GitHub, pull: GitHub -> 本地)"
        required: true
        type: "string"
        values: ["push", "pull"]
      - name: "id"
        description: "push操作时为本地路线图ID，pull操作时为远程项目Number"
        required: false
        type: "string"
    options:
      "--verbose":
        description: "显示详细输出"
        type: "flag"
        required: false
    expected_output: ["同步完成"]
    timeout: 30
    critical: true

  "roadmap switch":
    description: "切换活动路线图"
    arguments:
      - name: "roadmap_id"
        description: "路线图ID"
        required: false # Can be omitted to show current or clear
        type: "string"
    options:
      "--show":
        description: "只显示当前活动路线图"
        type: "flag"
        required: false
      "--clear":
        description: "清除当前活动路线图设置"
        type: "flag"
        required: false
    expected_output: ["已切换路线图", "当前活动路线图"]
    timeout: 5
    critical: true

  "roadmap list":
    description: "列出路线图元素或所有路线图"
    # No positional arguments
    options:
      "--all":
        description: "列出所有路线图而非当前路线图中的元素"
        type: "flag"
        required: false
      "--type":
        description: "元素类型"
        values: ["all", "milestone", "story", "task"]
        default: "all"
        required: false
        type: "string"
      "--status":
        description: "按状态筛选"
        required: false
        type: "string"
      "--assignee":
        description: "按负责人筛选"
        required: false
        type: "string"
      "--labels":
        description: "按标签筛选，多个标签用逗号分隔"
        required: false
        type: "string"
      "--detail":
        description: "显示详细信息"
        type: "flag"
        required: false
      "--format":
        description: "输出格式"
        values: ["text", "json", "table"]
        default: "text"
        required: false
        type: "string"
      "--verbose":
        description: "显示详细信息"
        type: "flag"
        required: false
    expected_output: ["路线图列表"]
    timeout: 10
    critical: true

  "roadmap create":
    description: "创建新的路线图元素 (用法: roadmap create [OPTIONS] {milestone|epic|story} TITLE)"
    arguments:
      - name: "element_type"
        description: "要创建的元素类型"
        required: true
        values: ["milestone", "epic", "story"]
        type: "string"
      - name: "title"
        description: "元素标题"
        required: true
        type: "string"
    options:
      "--epic":
        description: "所属史诗ID (用于story)"
        required: false
        type: "string"
      "--desc":
        description: "详细描述"
        required: false
        type: "string"
      "--assignee":
        description: "指派给用户"
        required: false
        type: "string"
      "--labels":
        description: "标签列表，用逗号分隔"
        required: false
        type: "string"
      "--priority":
        description: "优先级"
        values: ["high", "medium", "low"]
        required: false
        type: "string"
    expected_output: ["创建成功"]
    timeout: 10
    critical: true

  "roadmap update":
    description: "更新路线图元素状态 (用法: roadmap update [OPTIONS] {milestone|story|task} ID STATUS)"
    arguments:
      - name: "element_type"
        description: "要更新的元素类型"
        required: true
        values: ["milestone", "story", "task"]
        type: "string"
      - name: "element_id"
        description: "元素ID"
        required: true
        type: "string"
      - name: "status"
        description: "新的状态"
        required: true
        type: "string" # Define specific values if needed
    options:
      "--sync":
        description: "同步到GitHub"
        type: "flag"
        required: false
      "--comment":
        description: "更新说明"
        required: false
        type: "string"
      "--assignee":
        description: "更新指派人"
        required: false
        type: "string"
      "--labels":
        description: "更新标签（用逗号分隔）"
        required: false
        type: "string"
    expected_output: ["更新成功"]
    timeout: 10
    critical: true

  "roadmap story":
    description: "管理路线图故事"
    arguments:
      - name: "story_id"
        description: "故事ID (可选，不提供则可能列出所有故事或基于上下文)"
        required: false
        type: "string"
    options:
      "--title":
        description: "故事标题"
        required: false
        type: "string"
      "--milestone":
        description: "所属里程碑ID"
        required: false
        type: "string"
      "--desc":
        description: "故事描述"
        required: false
        type: "string"
      "--priority":
        description: "优先级"
        values: ["P0", "P1", "P2", "P3"]
        required: false
        type: "string"
      "--assignee":
        description: "指派给用户"
        required: false
        type: "string"
      "--labels":
        description: "标签列表，用逗号分隔"
        required: false
        type: "string"
      "--status":
        description: "更新状态"
        values: ["not_started", "in_progress", "completed", "blocked"]
        required: false
        type: "string"
      "--comment":
        description: "状态变更说明"
        required: false
        type: "string"
      "--format":
        description: "输出格式"
        values: ["json", "text", "table"]
        default: "text"
        required: false
        type: "string"
      "--delete":
        description: "删除故事"
        type: "flag"
        required: false
      "--force":
        description: "强制删除，不请求确认"
        type: "flag"
        required: false
    expected_output: ["故事详情", "更新成功", "删除成功"]
    timeout: 10
    critical: true

  "roadmap validate":
    description: "验证路线图YAML文件"
    arguments:
      - name: "source_file"
        description: "源文件路径"
        required: true
        type: "string"
    options:
      "--fix":
        description: "自动修复格式问题"
        type: "flag"
        required: false
      "--output":
        description: "修复后输出的文件路径"
        required: false
        type: "string"
      "--template":
        description: "使用自定义模板验证"
        required: false
        type: "string"
      "--verbose":
        description: "显示详细信息"
        type: "flag"
        required: false
      "--import":
        description: "验证通过后导入路线图"
        type: "flag"
        required: false
      "--roadmap-id":
        description: "导入时指定路线图ID"
        required: false
        type: "string"
    expected_output: ["验证通过", "验证失败"]
    timeout: 15
    critical: true

  "roadmap import":
    description: "导入路线图YAML文件"
    arguments:
      - name: "source_file"
        description: "源文件路径"
        required: true
        type: "string"
    options:
      "--roadmap-id":
        description: "现有路线图ID"
        required: false
        type: "string"
      "--fix":
        description: "自动修复格式问题"
        type: "flag"
        required: false
      "--activate":
        description: "导入后设为当前活动路线图"
        type: "flag"
        required: false
      "--verbose":
        description: "显示详细信息"
        type: "flag"
        required: false
    expected_output: ["导入成功"]
    timeout: 20
    critical: true

  "roadmap show":
    description: "查看路线图详情"
    # Optional positional argument? Or only options?
    # Assuming only options for now based on lack of explicit args in desc.
    arguments: [] # Explicitly empty
    options:
      "--id":
        description: "路线图ID"
        required: false
        type: "string"
      "--milestone":
        description: "里程碑ID"
        required: false
        type: "string"
      "--task":
        description: "任务ID"
        required: false
        type: "string"
      "--health":
        description: "显示健康状态检查"
        type: "flag"
        required: false
      "--format":
        description: "输出格式"
        values: ["json", "text", "table"]
        default: "table"
        required: false
        type: "string"
    expected_output: ["路线图详情"]
    timeout: 10
    critical: true

  "roadmap export":
    description: "导出路线图为YAML"
    # Optional positional argument for roadmap ID?
    arguments:
      - name: "roadmap_id" # Assuming ID can be positional or via --id
        description: "要导出的路线图ID (可选，也可用 --id)"
        required: false
        type: "string"
    options:
      "--id": # Allow specifying via option too
        description: "要导出的路线图ID"
        required: false
        type: "string"
      "--output":
        description: "输出文件路径"
        required: true
        type: "string"
      "--milestone":
        description: "只导出特定里程碑及其任务"
        required: false
        type: "string"
      "--template":
        description: "使用特定模板格式"
        required: false
        type: "string"
    expected_output: ["导出成功"]
    timeout: 15
    critical: true

  "roadmap delete":
    description: "删除路线图或元素 (用法: roadmap delete [OPTIONS] {roadmap|milestone|task} ID)"
    arguments:
      - name: "element_type"
        description: "要删除的元素类型"
        required: true
        values: ["roadmap", "milestone", "task"]
        type: "string"
      - name: "element_id"
        description: "元素ID"
        required: true
        type: "string"
    options:
      "--force":
        description: "强制删除，不请求确认"
        type: "flag"
        required: false
      "--cascade":
        description: "级联删除关联元素"
        type: "flag"
        required: false
    expected_output: ["删除成功"]
    timeout: 10
    critical: true

  "roadmap plan":
    description: "互动式路线图规划"
    arguments: [] # Assuming interactive mode doesn't use positional args
    options:
      "--id":
        description: "要修改的路线图ID"
        required: false
        type: "string"
      "--template":
        description: "使用特定模板开始"
        required: false
        type: "string"
      "--from":
        description: "从YAML文件开始"
        required: false
        type: "string"
      "--interactive":
        description: "始终使用交互式模式"
        type: "flag"
        required: false
    expected_output: ["规划完成"]
    timeout: 30
    critical: true

# 路线图命令组配置
group_config:
  max_concurrent_roadmaps: 5    # 最大并发路线图数
  auto_backup: true            # 自动备份
  sync_interval: 3600         # GitHub同步间隔（秒）
  default_format: "table"     # 默认输出格式

# 验证配置
validation:
  check_dependencies: true    # 检查依赖关系
  validate_status: true      # 验证状态转换
  check_permissions: true    # 检查权限
  enforce_naming: true       # 强制命名规范
