# 规则命令组配置

commands:
  "rule list":
    description: "列出所有规则"
    subcommands:
      "--type":
        description: "按类型筛选规则"
        values: ["core", "dev", "tech", "tool"]
      "--format":
        description: "输出格式"
        values: ["table", "json", "yaml"]
      "--verbose":
        description: "显示详细信息"
        type: "flag"
    expected_output: ["规则列表", "规则类型", "规则名称"]
    timeout: 5
    critical: true

  "rule show":
    description: "显示规则详情"
    arguments:
      - name: "rule_name"
        description: "规则名称"
        required: true
    subcommands:
      "--format":
        description: "输出格式"
        values: ["markdown", "json", "yaml"]
      "--raw":
        description: "显示原始内容"
        type: "flag"
    expected_output: ["规则详情", "规则内容"]
    timeout: 5
    critical: true

  "rule create":
    description: "创建新规则"
    arguments:
      - name: "name"
        description: "规则名称"
        required: true
      - name: "type"
        description: "规则类型"
        required: true
    subcommands:
      "--description":
        description: "规则描述"
        type: "string"
      "--priority":
        description: "规则优先级"
        type: "integer"
    expected_output: ["规则创建成功", "成功"]
    timeout: 8
    critical: true

  "rule edit":
    description: "编辑规则"
    arguments:
      - name: "rule_name"
        description: "规则名称"
        required: true
    expected_output: ["打开规则", "编辑"]
    timeout: 10
    critical: true

  "rule delete":
    description: "删除规则"
    arguments:
      - name: "rule_name"
        description: "规则名称"
        required: true
    subcommands:
      "--force":
        description: "强制删除"
        type: "flag"
    expected_output: ["规则删除成功", "成功"]
    timeout: 5
    critical: true

  "rule enable":
    description: "启用规则"
    arguments:
      - name: "rule_name"
        description: "规则名称"
        required: true
    expected_output: ["启用规则", "成功"]
    timeout: 5
    critical: true

  "rule disable":
    description: "禁用规则"
    arguments:
      - name: "rule_name"
        description: "规则名称"
        required: true
    expected_output: ["禁用规则", "成功"]
    timeout: 5
    critical: true

# 命令组特定配置
group_config:
  allow_custom_rules: true      # 是否允许自定义规则
  max_rule_size: 1048576       # 规则文件最大大小（字节）
  auto_format: true            # 是否自动格式化规则文件
  backup_enabled: true         # 是否启用规则备份
  validate_on_save: true       # 保存时是否验证规则

# 规则模板配置
templates:
  agent:
    path: "templates/rule/agent.md"
    description: "代理规则模板"

  auto:
    path: "templates/rule/auto.md"
    description: "自动化规则模板"

  best_practices:
    path: "templates/rule/best_practices.md"
    description: "最佳实践规则模板"

  command:
    path: "templates/rule/command.md"
    description: "命令规则模板"

  role:
    path: "templates/rule/role_rule.md"
    description: "角色规则模板"

  workflow:
    path: "templates/rule/workflow.md"
    description: "工作流规则模板"

# 规则验证配置
validation:
  check_format: true           # 检查规则格式
  check_references: true       # 检查规则引用
  check_dependencies: true     # 检查规则依赖
  spell_check: true           # 拼写检查
  lint_markdown: true         # Markdown语法检查
