# 任务命令组配置

commands:
  "task list":
    description: "列出项目中的任务"
    arguments: [] # No positional arguments
    options:
      "--status":
        description: "按状态过滤"
        short: "-s"
        required: false
        type: "string"
      "--assignee":
        description: "按负责人过滤"
        short: "-a"
        required: false
        type: "string"
      "--label":
        description: "按标签过滤"
        short: "-l"
        multiple: true
        required: false
        type: "string"
      "--roadmap":
        description: "按关联的 Story ID 过滤"
        short: "-r"
        required: false
        type: "string"
      "--independent":
        description: "仅显示独立任务"
        short: "-i"
        type: "flag"
        required: false
      "--limit":
        description: "限制返回数量"
        type: "integer"
        required: false
      "--offset":
        description: "跳过指定数量的结果"
        type: "integer"
        required: false
      "--verbose":
        description: "显示更详细的信息"
        short: "-v"
        type: "flag"
        required: false
      "--format":
        description: "输出格式"
        values: ["yaml", "json"]
        required: false
        type: "string"
    expected_output: ["列出项目中的任务", "任务列表"]
    timeout: 5
    critical: true

  "task show":
    description: "显示任务详情"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
        type: "string"
    options:
      "--verbose":
        description: "显示更详细的信息"
        short: "-v"
        type: "flag"
        required: false
      "--format":
        description: "输出格式"
        values: ["yaml", "json"]
        required: false
        type: "string"
      "--log":
        description: "(假设) 显示相关日志"
        type: "flag"
        required: false
      "--ref":
        description: "(假设) 显示引用信息"
        type: "flag"
        required: false
      "--comments":
        description: "(假设) 显示评论"
        type: "flag"
        required: false
    expected_output: ["任务详情", "标题", "状态"]
    timeout: 5
    critical: true

  "task create":
    description: "创建新任务"
    arguments:
      - name: "title"
        description: "任务标题"
        required: true
        type: "string"
    options:
      "--desc":
        description: "任务描述"
        short: "-d"
        required: false
        type: "string"
      "--priority":
        description: "任务优先级"
        short: "-p"
        values: ["low", "medium", "high"]
        default: "medium"
        required: false
        type: "string"
      "--status":
        description: "任务状态"
        short: "-s"
        values: ["todo", "in_progress", "done"]
        default: "todo"
        required: false
        type: "string"
      "--due":
        description: "任务截止日期 (格式: YYYY-MM-DD，默认为创建日期后3天)"
        required: false
        type: "string"
      "--link-story":
        description: "关联到Story"
        required: false
        type: "string"
      "--link-github":
        short: "-g"
        description: "关联到GitHub Issue (格式: owner/repo#number)"
        required: false
        type: "string"
      "--flow":
        description: "创建并关联工作流会话"
        short: "-f"
        values: ["dev", "review", "deploy"]
        required: false
        type: "string"
      "--verbose":
        description: "显示详细信息"
        short: "-v"
        type: "flag"
        required: false
    expected_output: ["创建", "任务", "成功"]
    timeout: 8
    critical: true

  "task update":
    description: "更新任务信息"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
        type: "string"
    options:
      "--title":
        description: "新的任务标题"
        short: "-t"
        required: false
        type: "string"
      "--desc":
        description: "新的任务描述"
        short: "-d"
        required: false
        type: "string"
      "--status":
        description: "新的状态"
        short: "-s"
        required: false
        type: "string"
      "--assignee":
        description: "新的负责人"
        short: "-a"
        required: false
        type: "string"
      "--labels":
        description: "设置新的标签列表"
        short: "-l"
        multiple: true
        required: false
        type: "string"
      "--due":
        description: "任务截止日期 (格式: YYYY-MM-DD，设置为'clear'可清除截止日期)"
        aliases: ["--due-date"]
        required: false
        type: "string"
      "--link-story":
        description: "关联到Story"
        short: "-s"
        required: false
        type: "string"
      "--link-github":
        description: "关联到GitHub Issue (格式: owner/repo#number)"
        short: "-g"
        required: false
        type: "string"
      "--unlink":
        description: "取消关联"
        values: ["story", "github"]
        required: false
        type: "string"
    expected_output: ["更新", "任务", "成功"]
    timeout: 8
    critical: true

  "task delete":
    description: "删除指定的任务"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
        type: "string"
    options:
      "--force":
        description: "强制删除"
        short: "-f"
        type: "flag"
        required: false
    expected_output: ["删除", "任务", "成功"]
    timeout: 5
    critical: true

  "task comment":
    description: "添加任务评论"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
        type: "string"
    options:
      "--comment":
        description: "评论内容"
        short: "-c"
        required: true # Keep required as true based on original
        type: "string"
    expected_output: ["评论", "添加", "成功"]
    timeout: 5
    critical: true

  "task link":
    description: "管理任务的工作流会话"
    arguments:
      - name: "task_id"
        description: "任务ID，不指定则使用当前任务"
        required: false
        type: "string"
    options:
      "--flow":
        description: "创建新的工作流会话"
        short: "-f"
        values: ["dev", "review", "deploy"]
        required: false
        type: "string"
      "--session":
        description: "关联到已存在的会话"
        short: "-s"
        required: false
        type: "string"
    expected_output: ["关联", "工作流", "成功"]
    timeout: 5
    critical: true

# 命令组特定配置
group_config:
  default_status: "open"        # 默认任务状态
  allow_multiple_assignees: false  # 是否允许多个负责人
  max_description_length: 2000  # 描述最大长度
  allow_task_dependencies: true # 是否允许任务依赖
  enable_task_templates: true   # 是否启用任务模板
  default_due_date_days: 3      # 默认截止日期天数
