# 任务命令组配置

commands:
  "task list":
    description: "列出项目中的任务"
    subcommands:
      "--status":
        description: "按状态过滤"
        short: "-s"
      "--assignee":
        description: "按负责人过滤"
        short: "-a"
      "--label":
        description: "按标签过滤"
        short: "-l"
        multiple: true
      "--roadmap":
        description: "按关联的 Story ID 过滤"
        short: "-r"
      "--independent":
        description: "仅显示独立任务"
        short: "-i"
        type: "flag"
      "--limit":
        description: "限制返回数量"
        type: "integer"
      "--offset":
        description: "跳过指定数量的结果"
        type: "integer"
      "--verbose":
        description: "显示更详细的信息"
        short: "-v"
        type: "flag"
      "--format":
        description: "输出格式"
        values: ["yaml", "json"]
    expected_output: ["列出项目中的任务", "任务列表"]
    timeout: 5
    critical: true

  "task show":
    description: "显示任务详情"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
    subcommands:
      "--verbose":
        description: "显示更详细的信息"
        short: "-v"
        type: "flag"
      "--format":
        description: "输出格式"
        values: ["yaml", "json"]
    expected_output: ["任务详情", "标题", "状态"]
    timeout: 5
    critical: true

  "task create":
    description: "创建新任务"
    arguments:
      - name: "title"
        description: "任务标题"
        required: true
    subcommands:
      "--desc":
        description: "任务描述"
        short: "-d"
      "--priority":
        description: "任务优先级"
        short: "-p"
        values: ["low", "medium", "high"]
        default: "medium"
      "--status":
        description: "任务状态"
        short: "-s"
        values: ["todo", "in_progress", "done"]
        default: "todo"
      "--link-story":
        description: "关联到Story"
      "--link-github":
        description: "关联到GitHub Issue (格式: owner/repo#number)"
      "--flow":
        description: "创建并关联工作流会话"
        short: "-f"
        values: ["dev", "review", "deploy"]
      "--verbose":
        description: "显示详细信息"
        short: "-v"
        type: "flag"
    expected_output: ["创建", "任务", "成功"]
    timeout: 8
    critical: true

  "task update":
    description: "更新任务信息"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
    subcommands:
      "--title":
        description: "新的任务标题"
        short: "-t"
      "--desc":
        description: "新的任务描述"
        short: "-d"
      "--status":
        description: "新的状态"
        short: "-s"
      "--assignee":
        description: "新的负责人"
        short: "-a"
      "--label":
        description: "设置新的标签列表"
        short: "-l"
        multiple: true
      "--add-label":
        description: "添加标签"
        multiple: true
      "--remove-label":
        description: "移除标签"
        multiple: true
      "--link-story":
        description: "关联到Story"
        short: "-s"
      "--link-github":
        description: "关联到GitHub Issue (格式: owner/repo#number)"
        short: "-g"
      "--unlink":
        description: "取消关联"
        values: ["story", "github"]
    expected_output: ["更新", "任务", "成功"]
    timeout: 8
    critical: true

  "task delete":
    description: "删除指定的任务"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
    subcommands:
      "--force":
        description: "强制删除"
        short: "-f"
        type: "flag"
    expected_output: ["删除", "任务", "成功"]
    timeout: 5
    critical: true

  "task comment":
    description: "添加任务评论"
    arguments:
      - name: "task_id"
        description: "任务ID"
        required: true
    subcommands:
      "--comment":
        description: "评论内容"
        short: "-c"
        required: true
    expected_output: ["评论", "添加", "成功"]
    timeout: 5
    critical: true

  "task link":
    description: "管理任务的工作流会话"
    arguments:
      - name: "task_id"
        description: "任务ID，不指定则使用当前任务"
        required: false
    subcommands:
      "--flow":
        description: "创建新的工作流会话"
        short: "-f"
        values: ["dev", "review", "deploy"]
      "--session":
        description: "关联到已存在的会话"
        short: "-s"
    expected_output: ["关联", "工作流", "成功"]
    timeout: 5
    critical: true

# 命令组特定配置
group_config:
  default_status: "open"        # 默认任务状态
  allow_multiple_assignees: false  # 是否允许多个负责人
  max_description_length: 2000  # 描述最大长度
  allow_task_dependencies: true # 是否允许任务依赖
  enable_task_templates: true   # 是否启用任务模板
