name: task
description: "任务管理命令 (类似 GitHub issue)"
type: group
subcommands:
  list:
    description: "列出和过滤任务"
    options:
      - name: status
        short: s
        description: "按状态过滤 (例如: open,in_progress)"
        required: false
        multiple: true
      - name: assignee
        short: a
        description: "按负责人过滤"
        required: false
      - name: label
        short: l
        description: "按标签过滤 (目前仅简单匹配)"
        required: false
        multiple: true
      - name: roadmap
        short: r
        description: "按关联的 Story ID 过滤"
        required: false
      - name: independent
        short: i
        description: "仅显示独立任务 (无 Roadmap 关联)"
        required: false
        type: flag
      - name: limit
        description: "限制返回数量"
        required: false
        type: integer
      - name: offset
        description: "跳过指定数量的结果"
        required: false
        type: integer
      - name: verbose
        short: v
        description: "显示更详细的信息"
        required: false
        type: flag

  show:
    description: "显示任务详情"
    args:
      - name: task_id
        description: "要显示的任务ID"
        required: true
    options:
      - name: verbose
        short: v
        description: "显示更详细的信息，包括评论"
        required: false
        type: flag

  create:
    description: "创建新任务"
    options:
      - name: title
        short: t
        description: "任务标题"
        required: true
      - name: desc
        short: d
        description: "任务描述"
        required: false
      - name: assignee
        short: a
        description: "负责人"
        required: false
      - name: label
        short: l
        description: "标签 (可多次使用)"
        required: false
        multiple: true
      - name: status
        short: s
        description: "初始状态 (默认: open)"
        required: false
      - name: link-roadmap
        description: "关联到 Story ID"
        required: false
      - name: link-workflow-stage
        description: "关联到 Workflow Stage Instance ID"
        required: false
      - name: link-github
        description: "关联到 GitHub Issue (格式: owner/repo#number)"
        required: false

  update:
    description: "更新任务信息"
    args:
      - name: task_id
        description: "要更新的任务ID"
        required: true
    options:
      - name: title
        short: t
        description: "新的任务标题"
        required: false
      - name: desc
        short: d
        description: "新的任务描述"
        required: false
      - name: assignee
        short: a
        description: "新的负责人 ('-' 表示清空)"
        required: false
      - name: label
        short: l
        description: "设置新的标签列表 (覆盖旧列表)"
        required: false
        multiple: true
      - name: add-label
        description: "添加标签"
        required: false
        multiple: true
      - name: remove-label
        description: "移除标签"
        required: false
        multiple: true
      - name: status
        short: s
        description: "新的状态"
        required: false

  delete:
    description: "删除任务"
    args:
      - name: task_id
        description: "要删除的任务ID"
        required: true
    options:
      - name: force
        short: f
        description: "跳过确认直接删除"
        required: false
        type: flag

  comment:
    description: "添加任务评论"
    args:
      - name: task_id
        description: "要评论的任务ID"
        required: true
    options:
      - name: comment
        short: c
        description: "要添加的评论"
        required: true

  link:
    description: "关联任务到其他实体"
    args:
      - name: task_id
        description: "要关联的任务ID"
        required: true
    options:
      - name: type
        short: t
        description: "关联类型 (roadmap/workflow_stage/github_issue/github_pr/github_commit)"
        required: true
      - name: target
        short: id
        description: "目标实体的标识符 ('-' 表示取消关联)"
        required: true
