# 数据库健康检查配置

# 数据库检查配置
database:
  # 核心系统表（优先级：P0）
  core_tables:
    - name: "rules"
      description: "规则表"
      min_records: 1
      priority: 0
      category: "core"
    - name: "templates"
      description: "模板表"
      min_records: 0
      priority: 0
      category: "core"
    - name: "memory_items"
      description: "记忆项表"
      min_records: 0
      priority: 0
      category: "core"

  # 工作流引擎表（优先级：P1）
  workflow_tables:
    - name: "workflows"
      description: "工作流定义表"
      min_records: 0
      priority: 1
      category: "workflow"
    - name: "stages"
      description: "工作流阶段表"
      min_records: 0
      priority: 1
      category: "workflow"
    - name: "transitions"
      description: "阶段转换表"
      min_records: 0
      priority: 1
      category: "workflow"
    - name: "workflow_definitions"
      description: "工作流模板表"
      min_records: 0
      priority: 1
      category: "workflow"

  # 会话管理表（优先级：P1）
  session_tables:
    - name: "flow_sessions"
      description: "流程会话表"
      min_records: 0
      priority: 1
      category: "session"
    - name: "stage_instances"
      description: "阶段实例表"
      min_records: 0
      priority: 1
      category: "session"

  # 任务管理表（优先级：P2）
  task_tables:
    - name: "stories"
      description: "用户故事表"
      min_records: 0
      priority: 2
      category: "task"
    - name: "tasks"
      description: "任务表"
      min_records: 0
      priority: 2
      category: "task"
    - name: "epics"
      description: "Epic表"
      min_records: 0
      priority: 2
      category: "task"

  # 路线图管理表（优先级：P2）
  roadmap_tables:
    - name: "roadmaps"
      description: "路线图表"
      min_records: 0
      priority: 2
      category: "roadmap"
    - name: "milestones"
      description: "里程碑表"
      min_records: 0
      priority: 2
      category: "roadmap"

# 数据库文件检查配置
files:
  required:
    - path: "src/db/connection_manager.py"
      description: "数据库连接管理"
      priority: 0
    - path: "src/db/repository.py"
      description: "数据库仓储基类"
      priority: 0
    - path: "src/db/service.py"
      description: "数据库服务基类"
      priority: 0
    - path: "src/db/README.md"
      description: "数据库模块说明文档"
      priority: 1
    - path: "src/db/models/__init__.py"
      description: "数据模型包"
      priority: 0
    - path: "src/db/repositories/__init__.py"
      description: "仓储实现包"
      priority: 0

# 检查配置
check_config:
  # 优先级定义
  priorities:
    P0: "核心功能，必须存在且正确"
    P1: "重要功能，建议完善"
    P2: "次要功能，可选完善"

  # 分类说明
  categories:
    core: "核心系统表，包含规则、模板等基础功能"
    workflow: "工作流引擎相关表，处理流程定义和执行"
    session: "会话管理相关表，处理运行时状态"
    task: "任务管理相关表，处理项目任务"
    roadmap: "路线图相关表，处理项目规划"

  # 检查行为配置
  behavior:
    check_table_existence: true
    check_record_count: true
    check_file_existence: true
    check_file_permissions: false  # 暂不检查文件权限
    check_table_schema: false      # 暂不检查表结构

  # 性能配置
  performance:
    connection_timeout: 5    # 秒
    query_timeout: 10       # 秒
    max_retry_count: 3      # 重试次数

# 数据完整性检查配置
integrity_checks:
  check_foreign_keys: true    # 是否检查外键完整性
  check_indexes: true         # 是否检查索引存在
  check_constraints: true     # 是否检查约束完整性

# 安全检查配置
security_checks:
  check_permissions: true     # 检查数据库权限
  check_encryption: true      # 检查是否启用加密
  check_backup: true         # 检查备份配置
