# 系统检查配置
environment:
  required_env_vars:
    - name: "VIBECOPILOT_ENV"
      default: "development"
      description: "运行环境"
    - name: "DB_PATH"
      default: "data/db/vibecopilot.db"
      description: "SQLite数据库路径"
    - name: "LOG_LEVEL"
      default: "INFO"
      description: "日志级别"

  optional_env_vars:
    - name: "CLAUDE_API_KEY"
      description: "Claude API密钥（可选）"
    - name: "VECTOR_DB_PATH"
      default: "data/vector_db"
      description: "向量数据库路径（可选）"
    - name: "PORT"
      default: "8000"
      description: "服务器端口（可选）"
    - name: "HOST"
      default: "localhost"
      description: "服务器主机名（可选）"

dependencies:
  python_version: ">=3.9.0"
  required_packages:
    - name: "sqlalchemy"
      min_version: "1.4.0"
    - name: "click"
      min_version: "8.0.0"
    - name: "python-dotenv"
      min_version: "0.19.0"
    - name: "pyyaml"
      min_version: "6.0.0"

  optional_packages:
    - name: "fastapi"
      min_version: "0.95.0"
      description: "API框架（可选）"

directories:
  required:
    - path: "src"
      description: "核心源代码目录"
    - path: "config"
      description: "配置文件目录"
    - path: "data"
      description: "数据存储目录"
    - path: ".ai"
      description: "AI相关资源"
    - path: "tests"
      description: "测试代码目录"

  optional:
    - path: "docs"
      description: "文档目录"
    - path: "scripts"
      description: "构建和工具脚本"

config_files:
  required:
    - path: ".env"
      description: "环境变量配置文件"
    - path: "requirements.txt"
      description: "Python依赖配置"
    - path: "README.md"
      description: "项目说明文档"

  optional:
    - path: "config/default/claude.json"
      description: "Claude API配置（可选）"
    - path: ".cursor/settings.json"
      description: "Cursor IDE配置（可选）"
    - path: ".ai/prompts/default.json"
      description: "AI提示配置（可选）"

performance:
  max_response_time: 30  # 秒
  check_response_time: true

output_format:
  check_json_format: true
  check_help_format: true
  check_error_format: true
