/**
 * 创建侧边栏可以很简单，通过标记文章中的front matter自动生成
 * https://docusaurus.io/docs/sidebar/autogenerated
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认将使用自动生成的侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
