name: 项目自动化工作流

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]
  schedule:
    - cron: '0 12 * * 5' # 每周五中午12点
  workflow_dispatch: # 允许手动触发

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/github/requirements.txt ]; then pip install -r scripts/github/requirements.txt; fi

      - name: 更新项目状态
        run: |
          if [ -f scripts/github/update_project_status.py ]; then
            python scripts/github/update_project_status.py
          else
            echo "项目状态更新脚本不存在，请先创建"
          fi

      - name: 分析项目风险
        run: |
          if [ -f scripts/github/analyze_project.py ]; then
            python scripts/github/analyze_project.py --metrics "progress,quality,risks" --output analysis.json
          else
            echo "项目分析脚本不存在，请先创建"
          fi

      - name: 生成状态报告
        run: |
          if [ -f scripts/github/generate_report.py ]; then
            python scripts/github/generate_report.py --format markdown --input analysis.json
          else
            echo "报告生成脚本不存在，请先创建"
          fi

      - name: 调整路线图
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          if [ -f scripts/github/adjust_timeline.py ]; then
            python scripts/github/adjust_timeline.py --based-on-analysis analysis.json --update-milestones true
          else
            echo "路线图调整脚本不存在，请先创建"
          fi
