name: Test All

on:
  workflow_dispatch:
  schedule:
    # 每周日中午运行
    - cron: '0 12 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pytest pytest-cov

    - name: Run database tests
      run: |
        python -m pytest tests/db -v

    - name: Run validation tests
      run: |
        python -m pytest tests/validation -v

    - name: Run template tests
      run: |
        python -m pytest tests/templates -v

    - name: Run integration tests
      run: |
        python -m pytest tests/integration -v

    - name: Run CLI tests
      run: |
        python -m pytest tests/cli -v

    - name: Run all other tests
      run: |
        python -m pytest tests/core tests/unit tests/workflow tests/parsing -v

    - name: Generate coverage report
      run: |
        python -m pytest --cov=src tests/

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.10'
      with:
        fail_ci_if_error: false
